apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: "kubernetes"
    jenkins/label-digest: "91a837507692599c55f75b8ac33c184716af70a9"
    jenkins/label: "jenkins"
spec:
  containers:
  - name: jnlp
    image: gcr.io/natural-ethos-452/jenkins-slave
    imagePullPolicy: "Always"
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    env:
     - name: "JENKINS_WEB_SOCKET"
       value: "true"
     - name: "JENKINS_AGENT_WORKDIR"
       value: "/home/jenkins"
     - name: "JENKINS_URL"
       value: "https://axumt.com/jenkins/"
    resources:
        limits:
          memory: 200Mi
          cpu: 90m
        requests:
          cpu: 40m
          memory: 100Mi
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
    resources:
        limits:
          memory: 256Mi
          cpu: 100m
        requests:
          cpu: 50m
          memory: 120Mi

